### ISSUE TITLE
TimeCount - NoClassDefFoundError

### ISSUE THREAD

**Issue by songly** [LinkedInAttic/datafu#32]
When I use datafu.pig.date.TimeCount. I get this problem:
![2013-05-18 4 15 41 pm](https://f.cloud.github.com/assets/283273/521302/2f7b065e-bf93-11e2-9439-65cd6cede71a.png)

**Comment by matthayes** [comment]
Is the joda-time JAR in the classpath?

**Comment by samshah** [comment]
Let us know if you're still having a problem.
