### ISSUE TITLE
Unable to create UDF with optional 2nd argument

### ISSUE THREAD

**Issue by rjurney** [LinkedInAttic/datafu#85]
How can I create a UDF with an optional 2nd argument? Two call() methods isn't working.

**Comment by matthayes** [comment]
You could create two constructors.  One constructor has one argument and the other constructor has two arguments.

**Comment by rjurney** [comment]
I've tried that. There are two problems:

1) I have to catch an IOException to call call()
2) I have to return something to call call().

Hmmm I'll try again. Neither of those should block me.

On Sun, Jan 5, 2014 at 12:12 PM, Matt Hayes notifications@github.comwrote:

> You could create two constructors. One constructor has one argument and
> the other constructor has two arguments.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/linkedin/datafu/issues/85#issuecomment-31614088
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by matthayes** [comment]
Oh I misunderstood I think.  I thought you meant the constructor.  Are you using SimpleEvalFunc?  I don't think it supports this use case of a 2nd optional argument.  If you look in the implementation of exec() you see this

```
// check right number of arguments
if (input.size() != pvec.length)
  throw new IOException(String.format("%s: got %d arguments, expected %d.", _method_signature(), input.size(), pvec.length));
```

It expects there to be a call() method and it checks that the input tuple has the same number of values as there are arguments in the call() method.

I suggest just using EvalFunc then if you want optional parameters.

**Comment by rjurney** [comment]
I thnk I made it work as you suggested. Testing now, but need to know how
to run just one test or it takes a half hour.

On Sunday, January 5, 2014, Matt Hayes wrote:

> Oh I misunderstood I think. I thought you meant the constructor. Are you
> using SimpleEvalFunc? I don't think it supports this use case of a 2nd
> optional argument. If you look in the implementation of exec() you see this
> 
> // check right number of arguments
> if (input.size() != pvec.length)
>   throw new IOException(String.format("%s: got %d arguments, expected %d.", _method_signature(), input.size(), pvec.length));
> 
> It expects there to be a call() method and it checks that the input tuple
> has the same number of values as there are arguments in the call() method.
> 
> I suggest just using EvalFunc then if you want optional parameters.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/linkedin/datafu/issues/85#issuecomment-31614362
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by rjurney** [comment]
Using two constructors doesn't work. I am using SimpleEvalFunc. Ok, I will try using EvalFunc.

**Comment by rjurney** [comment]
Is there some way to modify SimpleEvalFunc so that I can use two constructors? I like using it.

**Comment by matthayes** [comment]
I think you should be able to have multiple constructors with SimpleEvalFunc.  You just can't have multiple overloaded call implementations.  You just need to ensure each calls super().  What is the problem you are having?

**Comment by rjurney** [comment]
I created call(String input) that calls call(String input, String path)
with default path. It fails with the same error as before: expected 2, got
1.

On Sunday, January 5, 2014, Matt Hayes wrote:

> I think you should be able to have multiple constructors with
> SimpleEvalFunc. You just can't have multiple overloaded call
> implementations. You just need to ensure each calls super(). What is the
> problem you are having?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/linkedin/datafu/issues/85#issuecomment-31614937
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com

**Comment by matthayes** [comment]
the call method is not a constructor

**Comment by rjurney** [comment]
Good call. Lemme take another look.

On Sunday, January 5, 2014, Matt Hayes wrote:

> the call method is not a constructor
> 
> > On Jan 5, 2014, at 1:11 PM, Russell Jurney <notifications@github.com<javascript:_e({}, 'cvml', 'notifications@github.com');>>
> > wrote:
> > 
> > I created call(String input) that calls call(String input, String path)
> > with default path. It fails with the same error as before: expected 2,
> > got
> > 1.
> > 
> > On Sunday, January 5, 2014, Matt Hayes wrote:
> > 
> > > I think you should be able to have multiple constructors with
> > > SimpleEvalFunc. You just can't have multiple overloaded call
> > > implementations. You just need to ensure each calls super(). What is
> > > the
> > > problem you are having?
> > > 
> > > \
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/linkedin/datafu/issues/85#issuecomment-31614937>
> > > .
> > 
> > ## 
> > 
> > Russell Jurney twitter.com/rjurney russell.jurney@gmail.com<javascript:_e({}, 'cvml', 'russell.jurney@gmail.com');>
> > datasyndrome.com
> > \
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/linkedin/datafu/issues/85#issuecomment-31616199
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com
