### ISSUE TITLE
Can't run one unit test

### ISSUE THREAD

**Issue by rjurney** [LinkedInAttic/datafu#86]
How do I run one unit test at a time?

**Comment by matthayes** [comment]
From the command line, like this:

ant test -Dtest.methods=datafu.test.pig.stats.QuantileTests.quantileTest

But when developing test cases it is probably easier to run in eclipse.

**Comment by rjurney** [comment]
Thanks!

On Sunday, January 5, 2014, Matt Hayes wrote:

> From the command line, like this:
> 
> ant test -Dtest.methods=datafu.test.pig.stats.QuantileTests.quantileTest
> 
> But when developing test cases it is probably easier to run in eclipse.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/linkedin/datafu/issues/86#issuecomment-31614430
> .

## 

Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com
