### ISSUE TITLE
Upgrade Pig library used to 0.12

### ISSUE THREAD

**Issue by rjurney** [LinkedInAttic/datafu#90]
I have a UDF which requires DataType.BIGDECIMAL/BIGINTEGER support, which was introduced in 0.12.

**Comment by matthayes** [comment]
I'm very hesitant to upgrade until Pig 0.12.1 is released (due to [PIG-3512](https://issues.apache.org/jira/browse/PIG-3512)).  Also if you like you may now create JIRAs in Apache's JIRA :) https://issues.apache.org/jira/browse/DATAFU
