### ISSUE TITLE
datafu.pig.sampling.ReservoirSample

### ISSUE THREAD

**Issue by basiamucha** [LinkedInAttic/datafu#92]
HI when using ReservoirSample it seems like the sample is done on the full input instead of the group input.

e.g. Lets say my input.txt is 
a1,5
a1,6
a1,7
a2,5
a2,6
a2,7

I have the following program:
DEFINE SRS datafu.pig.sampling.ReservoirSample('2');
data = LOAD 'input.txt' USING PigStorage(',') AS (key: chararray, value: chararray);
grouped = GROUP data BY key;
sample2 = FOREACH grouped GENERATE FLATTEN(SRS(data));

The output was. I would assume that that for each group it would sample (meaning I would see 2 samples of a1 and 2 samples of a2...why is that not)?
(a1,7)
(a1,6)
(a1,6)
(a1,6)

**Comment by william-g-vaughan** [comment]
Thank you for your report.  This is clearly a bug, and I've confirmed that
I can reproduce the behavior.  I've filed the issue here:
https://issues.apache.org/jira/browse/DATAFU-11

**Comment by basiamucha** [comment]
I have found a way to fix it:

In the Intermediate and Final function all we need is to reset reservoir back to new Reservoir.
    @Override
    public Tuple exec(Tuple input) throws IOException {
      //Reset reservoir for each Group By if not using Group BY ALL
      reservoir = new Reservoir(this.numSamples);

   @Override
    public DataBag exec(Tuple input) throws IOException {
      //Reset reservoir for each Group By if not using Group BY ALL
      reservoir = new Reservoir(this.numSamples);

I am using it currently for the way we want to sample...it would be really nice if we can update datafu with this if everyone agrees.

Thanks,

**Comment by matthayes** [comment]
Closing as now tracked by [DATAFU-11](https://issues.apache.org/jira/browse/DATAFU-11).  We'll get this fixed in the next release.

**Comment by basiamucha** [comment]
Thank you...quick question is there anywhere we can download the changes from DATAFU-11 in github or? I would like to test them on our end?

**Comment by matthayes** [comment]
Sure, if you want just this fix you could download the patch attached to
the JIRA (
https://issues.apache.org/jira/secure/attachment/12624839/DATAFU-11-v2.patch)
and apply it to your local repo.  Or you could clone the Apache DataFu repo
https://git-wip-us.apache.org/repos/asf/incubator-datafu.git and build a
JAR with all the latest changes (includes DATAFU-11 fix).  The current code
should be backwards compatible.
