### ISSUE TITLE
possible error in getting started with hourglass documentation

### ISSUE THREAD

**Issue by kamaldeep-ebay** [LinkedInAttic/datafu#97]
Hi,

Can someone please tell me how  do i get started in hourglass with the sample problem mentioned in the guide - http://datafu.incubator.apache.org/docs/hourglass/getting-started.html

It says there - 

Your other option is to download the code and build the JAR yourself. After unzipping the archive, navigate to contrib/hourglass and build the JAR by running ant jar. The dependencies will be downloaded to lib/common.

But i don't see the contrib folder in the datafu-master.zip dir. Also i dont see `contrib folder after cloning git://git.apache.org/incubator-datafu.git

Could someone pls. help me with getting started in hourglass ? Much appreciated.

Also couldn't find any buiild.xml or targets anywhere . Not sure where i can run ant jar.

If there is another guide please point me to it.

Thanks

**Comment by matthayes** [comment]
Thanks for pointing this out!  I've filed the JIRA below to track this.  We migrated from Ant to Gradle for building these projects.  I'll update the documentation.  Please watch the JIRA below for updates.

https://issues.apache.org/jira/browse/DATAFU-89
